package com.luciano.cadastrarpessoa.demo.exception

class PersonNotFoundException(id: Long) : RuntimeException("Cardholder n√£o encontrado id: $id")
