package com.luciano.cadastropessoa.cadastrarpessoa.exception

class PersonNotFoundException(id: Long) : RuntimeException("Person n√£o encontrado id: $id")
